### ISSUE TITLE
Top 10 of a campaign using campaign id

### ISSUE THREAD

**Issue by deepnimma** [artifexdevstuff/TMIndiaBotApi#1]
@artifexdevstuff 
Campaign top 10 (or max possible with one request to tmio) using campaign id as a parameter

**Comment by artifex24** [comment]
fixed in [#f02dbce](https://github.com/TrackmaniaIndia/TMIndiaBotApi/commit/f02dbce980cddcfad448470a371f715fc37ab2fd)
